#===================================================================
# Spring Boot application configuration for development environment
#===================================================================

#server configuration
server:
  port: ${MyServer.PORT}

spring:
  application:
    name: job-finder

  # configuration for file upload limits
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  profiles:
    active: dev

  # Database configuration
  datasource:
    url: jdbc:postgresql://${MyServer.Database.HOST}/${MyServer.Database.DBNAME}
    username: ${MyServer.Database.USER}
    password: "${MyServer.Database.PASS}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Email  configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: oeunnimith@gmail.com
    password: cuqdabznyvchymfz
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  # Redis configuration
  data:
    redis:
      host: 127.0.0.1
      port: 6379

# token_key
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
